version = 0.1
[default.deploy.parameters]
stack_name = "resume-challenge-007"
s3_prefix = "resume-challenge-007"
region = "us-east-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM CAPABILITY_AUTO_EXPAND CAPABILITY_NAMED_IAM"
disable_rollback = true
image_repositories = []
