AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  auth-resources

  SAM Template for auth resourcess

Parameters:
  DynamoDBName:
    Type: "String"
    Default: "ResumeVisits004"
  ResumeLambdaDynamoRoleName:
    Type: "String"
    Default: "ResumeLambdaDynamoRole004"
  FunctionName:
    Type: "String"
    Default: "GetCounter004"
  ApiName:
    Type: "String"
    Default: "GetCounterApi004"
  AllowedOrigin:
    Type: "String"
    Default: "*"

Resources:
  DynamoDB:
    Type: AWS::Serverless::Application
    Properties:
      Parameters:
        DynamoDBName: !Ref DynamoDBName
      Location: dynamodb.yaml
  Auth:
    Type: AWS::Serverless::Application
    Properties:
      Parameters:
        DynamoTableName: !GetAtt DynamoDB.Outputs.DynamoTableName
        ResumeLambdaDynamoRoleName: !Ref ResumeLambdaDynamoRoleName
      Location: auth.yaml
    DependsOn: DynamoDB
  # Counter:
  #   Type: AWS::Serverless::Application
  #   Properties:
  #     Location: counter.yaml
  #     Parameters:
  #       AllowedOrigin: !Ref AllowedOrigin
  #       DynamoTableName: !GetAtt DynamoDB.Outputs.DynamoTableName
  #       FunctionName: !Ref FunctionName
  #       ApiName: !Ref ApiName
  #   DependsOn: [Auth, DynamoDB]
